
add_executable(test.scratch.fe.WindowsRegistry.controller
	test.scratch.fe.WindowsRegistry.controller.cpp
)

target_link_STLSoft(test.scratch.fe.WindowsRegistry.controller)

define_target_compile_options(test.scratch.fe.WindowsRegistry.controller)


# ############################## end of file ############################# #

